
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AnalysisResults': typeof import("../components/AnalysisResults.vue")['default']
    'AnalyzerForm': typeof import("../components/AnalyzerForm.vue")['default']
    'FeatureCard': typeof import("../components/FeatureCard.vue")['default']
    'Features': typeof import("../components/Features.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'Header': typeof import("../components/Header.vue")['default']
    'Hero': typeof import("../components/Hero.vue")['default']
    'LocationSelect': typeof import("../components/LocationSelect.vue")['default']
    'MetricsGrid': typeof import("../components/MetricsGrid.vue")['default']
    'TrustedBy': typeof import("../components/TrustedBy.vue")['default']
    'UrlAnalyzer': typeof import("../components/UrlAnalyzer.vue")['default']
    'UiAccordion': typeof import("../components/ui/accordion")['default']
    'UiAlertDialog': typeof import("../components/ui/alert-dialog")['default']
    'UiAlert': typeof import("../components/ui/alert")['default']
    'UiAspectRatio': typeof import("../components/ui/aspect-ratio")['default']
    'UiAvatar': typeof import("../components/ui/avatar")['default']
    'UiBadge': typeof import("../components/ui/badge")['default']
    'UiBreadcrumb': typeof import("../components/ui/breadcrumb")['default']
    'UiButton': typeof import("../components/ui/button")['default']
    'UiCalendar': typeof import("../components/ui/calendar")['default']
    'UiCard': typeof import("../components/ui/card")['default']
    'UiCarousel': typeof import("../components/ui/carousel")['default']
    'UiChart': typeof import("../components/ui/chart")['default']
    'UiCheckbox': typeof import("../components/ui/checkbox")['default']
    'UiCollapsible': typeof import("../components/ui/collapsible")['default']
    'UiCommand': typeof import("../components/ui/command")['default']
    'UiContextMenu': typeof import("../components/ui/context-menu")['default']
    'UiDialog': typeof import("../components/ui/dialog")['default']
    'UiDrawer': typeof import("../components/ui/drawer")['default']
    'UiDropdownMenu': typeof import("../components/ui/dropdown-menu")['default']
    'UiForm': typeof import("../components/ui/form")['default']
    'UiHoverCard': typeof import("../components/ui/hover-card")['default']
    'UiInputOtp': typeof import("../components/ui/input-otp")['default']
    'UiInput': typeof import("../components/ui/input")['default']
    'UiLabel': typeof import("../components/ui/label")['default']
    'UiMenubar': typeof import("../components/ui/menubar")['default']
    'UiNavigationMenu': typeof import("../components/ui/navigation-menu")['default']
    'UiPagination': typeof import("../components/ui/pagination")['default']
    'UiPopover': typeof import("../components/ui/popover")['default']
    'UiProgress': typeof import("../components/ui/progress")['default']
    'UiRadioGroup': typeof import("../components/ui/radio-group")['default']
    'UiResizable': typeof import("../components/ui/resizable")['default']
    'UiScrollArea': typeof import("../components/ui/scroll-area")['default']
    'UiSelect': typeof import("../components/ui/select")['default']
    'UiSeparator': typeof import("../components/ui/separator")['default']
    'UiSheet': typeof import("../components/ui/sheet")['default']
    'UiSkeleton': typeof import("../components/ui/skeleton")['default']
    'UiSlider': typeof import("../components/ui/slider")['default']
    'UiSonner': typeof import("../components/ui/sonner")['default']
    'UiSwitch': typeof import("../components/ui/switch")['default']
    'UiTable': typeof import("../components/ui/table")['default']
    'UiTabs': typeof import("../components/ui/tabs")['default']
    'UiTextarea': typeof import("../components/ui/textarea")['default']
    'UiToast': typeof import("../components/ui/toast")['default']
    'UiToaster': typeof import("../components/ui/toaster")['default']
    'UiToggleGroup': typeof import("../components/ui/toggle-group")['default']
    'UiToggle': typeof import("../components/ui/toggle")['default']
    'UiTooltip': typeof import("../components/ui/tooltip")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAnalysisResults': typeof import("../components/AnalysisResults.vue")['default']
    'LazyAnalyzerForm': typeof import("../components/AnalyzerForm.vue")['default']
    'LazyFeatureCard': typeof import("../components/FeatureCard.vue")['default']
    'LazyFeatures': typeof import("../components/Features.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyHeader': typeof import("../components/Header.vue")['default']
    'LazyHero': typeof import("../components/Hero.vue")['default']
    'LazyLocationSelect': typeof import("../components/LocationSelect.vue")['default']
    'LazyMetricsGrid': typeof import("../components/MetricsGrid.vue")['default']
    'LazyTrustedBy': typeof import("../components/TrustedBy.vue")['default']
    'LazyUrlAnalyzer': typeof import("../components/UrlAnalyzer.vue")['default']
    'LazyUiAccordion': typeof import("../components/ui/accordion")['default']
    'LazyUiAlertDialog': typeof import("../components/ui/alert-dialog")['default']
    'LazyUiAlert': typeof import("../components/ui/alert")['default']
    'LazyUiAspectRatio': typeof import("../components/ui/aspect-ratio")['default']
    'LazyUiAvatar': typeof import("../components/ui/avatar")['default']
    'LazyUiBadge': typeof import("../components/ui/badge")['default']
    'LazyUiBreadcrumb': typeof import("../components/ui/breadcrumb")['default']
    'LazyUiButton': typeof import("../components/ui/button")['default']
    'LazyUiCalendar': typeof import("../components/ui/calendar")['default']
    'LazyUiCard': typeof import("../components/ui/card")['default']
    'LazyUiCarousel': typeof import("../components/ui/carousel")['default']
    'LazyUiChart': typeof import("../components/ui/chart")['default']
    'LazyUiCheckbox': typeof import("../components/ui/checkbox")['default']
    'LazyUiCollapsible': typeof import("../components/ui/collapsible")['default']
    'LazyUiCommand': typeof import("../components/ui/command")['default']
    'LazyUiContextMenu': typeof import("../components/ui/context-menu")['default']
    'LazyUiDialog': typeof import("../components/ui/dialog")['default']
    'LazyUiDrawer': typeof import("../components/ui/drawer")['default']
    'LazyUiDropdownMenu': typeof import("../components/ui/dropdown-menu")['default']
    'LazyUiForm': typeof import("../components/ui/form")['default']
    'LazyUiHoverCard': typeof import("../components/ui/hover-card")['default']
    'LazyUiInputOtp': typeof import("../components/ui/input-otp")['default']
    'LazyUiInput': typeof import("../components/ui/input")['default']
    'LazyUiLabel': typeof import("../components/ui/label")['default']
    'LazyUiMenubar': typeof import("../components/ui/menubar")['default']
    'LazyUiNavigationMenu': typeof import("../components/ui/navigation-menu")['default']
    'LazyUiPagination': typeof import("../components/ui/pagination")['default']
    'LazyUiPopover': typeof import("../components/ui/popover")['default']
    'LazyUiProgress': typeof import("../components/ui/progress")['default']
    'LazyUiRadioGroup': typeof import("../components/ui/radio-group")['default']
    'LazyUiResizable': typeof import("../components/ui/resizable")['default']
    'LazyUiScrollArea': typeof import("../components/ui/scroll-area")['default']
    'LazyUiSelect': typeof import("../components/ui/select")['default']
    'LazyUiSeparator': typeof import("../components/ui/separator")['default']
    'LazyUiSheet': typeof import("../components/ui/sheet")['default']
    'LazyUiSkeleton': typeof import("../components/ui/skeleton")['default']
    'LazyUiSlider': typeof import("../components/ui/slider")['default']
    'LazyUiSonner': typeof import("../components/ui/sonner")['default']
    'LazyUiSwitch': typeof import("../components/ui/switch")['default']
    'LazyUiTable': typeof import("../components/ui/table")['default']
    'LazyUiTabs': typeof import("../components/ui/tabs")['default']
    'LazyUiTextarea': typeof import("../components/ui/textarea")['default']
    'LazyUiToast': typeof import("../components/ui/toast")['default']
    'LazyUiToaster': typeof import("../components/ui/toaster")['default']
    'LazyUiToggleGroup': typeof import("../components/ui/toggle-group")['default']
    'LazyUiToggle': typeof import("../components/ui/toggle")['default']
    'LazyUiTooltip': typeof import("../components/ui/tooltip")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AnalysisResults: typeof import("../components/AnalysisResults.vue")['default']
export const AnalyzerForm: typeof import("../components/AnalyzerForm.vue")['default']
export const FeatureCard: typeof import("../components/FeatureCard.vue")['default']
export const Features: typeof import("../components/Features.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const Hero: typeof import("../components/Hero.vue")['default']
export const LocationSelect: typeof import("../components/LocationSelect.vue")['default']
export const MetricsGrid: typeof import("../components/MetricsGrid.vue")['default']
export const TrustedBy: typeof import("../components/TrustedBy.vue")['default']
export const UrlAnalyzer: typeof import("../components/UrlAnalyzer.vue")['default']
export const UiAccordion: typeof import("../components/ui/accordion")['default']
export const UiAlertDialog: typeof import("../components/ui/alert-dialog")['default']
export const UiAlert: typeof import("../components/ui/alert")['default']
export const UiAspectRatio: typeof import("../components/ui/aspect-ratio")['default']
export const UiAvatar: typeof import("../components/ui/avatar")['default']
export const UiBadge: typeof import("../components/ui/badge")['default']
export const UiBreadcrumb: typeof import("../components/ui/breadcrumb")['default']
export const UiButton: typeof import("../components/ui/button")['default']
export const UiCalendar: typeof import("../components/ui/calendar")['default']
export const UiCard: typeof import("../components/ui/card")['default']
export const UiCarousel: typeof import("../components/ui/carousel")['default']
export const UiChart: typeof import("../components/ui/chart")['default']
export const UiCheckbox: typeof import("../components/ui/checkbox")['default']
export const UiCollapsible: typeof import("../components/ui/collapsible")['default']
export const UiCommand: typeof import("../components/ui/command")['default']
export const UiContextMenu: typeof import("../components/ui/context-menu")['default']
export const UiDialog: typeof import("../components/ui/dialog")['default']
export const UiDrawer: typeof import("../components/ui/drawer")['default']
export const UiDropdownMenu: typeof import("../components/ui/dropdown-menu")['default']
export const UiForm: typeof import("../components/ui/form")['default']
export const UiHoverCard: typeof import("../components/ui/hover-card")['default']
export const UiInputOtp: typeof import("../components/ui/input-otp")['default']
export const UiInput: typeof import("../components/ui/input")['default']
export const UiLabel: typeof import("../components/ui/label")['default']
export const UiMenubar: typeof import("../components/ui/menubar")['default']
export const UiNavigationMenu: typeof import("../components/ui/navigation-menu")['default']
export const UiPagination: typeof import("../components/ui/pagination")['default']
export const UiPopover: typeof import("../components/ui/popover")['default']
export const UiProgress: typeof import("../components/ui/progress")['default']
export const UiRadioGroup: typeof import("../components/ui/radio-group")['default']
export const UiResizable: typeof import("../components/ui/resizable")['default']
export const UiScrollArea: typeof import("../components/ui/scroll-area")['default']
export const UiSelect: typeof import("../components/ui/select")['default']
export const UiSeparator: typeof import("../components/ui/separator")['default']
export const UiSheet: typeof import("../components/ui/sheet")['default']
export const UiSkeleton: typeof import("../components/ui/skeleton")['default']
export const UiSlider: typeof import("../components/ui/slider")['default']
export const UiSonner: typeof import("../components/ui/sonner")['default']
export const UiSwitch: typeof import("../components/ui/switch")['default']
export const UiTable: typeof import("../components/ui/table")['default']
export const UiTabs: typeof import("../components/ui/tabs")['default']
export const UiTextarea: typeof import("../components/ui/textarea")['default']
export const UiToast: typeof import("../components/ui/toast")['default']
export const UiToaster: typeof import("../components/ui/toaster")['default']
export const UiToggleGroup: typeof import("../components/ui/toggle-group")['default']
export const UiToggle: typeof import("../components/ui/toggle")['default']
export const UiTooltip: typeof import("../components/ui/tooltip")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAnalysisResults: typeof import("../components/AnalysisResults.vue")['default']
export const LazyAnalyzerForm: typeof import("../components/AnalyzerForm.vue")['default']
export const LazyFeatureCard: typeof import("../components/FeatureCard.vue")['default']
export const LazyFeatures: typeof import("../components/Features.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyHero: typeof import("../components/Hero.vue")['default']
export const LazyLocationSelect: typeof import("../components/LocationSelect.vue")['default']
export const LazyMetricsGrid: typeof import("../components/MetricsGrid.vue")['default']
export const LazyTrustedBy: typeof import("../components/TrustedBy.vue")['default']
export const LazyUrlAnalyzer: typeof import("../components/UrlAnalyzer.vue")['default']
export const LazyUiAccordion: typeof import("../components/ui/accordion")['default']
export const LazyUiAlertDialog: typeof import("../components/ui/alert-dialog")['default']
export const LazyUiAlert: typeof import("../components/ui/alert")['default']
export const LazyUiAspectRatio: typeof import("../components/ui/aspect-ratio")['default']
export const LazyUiAvatar: typeof import("../components/ui/avatar")['default']
export const LazyUiBadge: typeof import("../components/ui/badge")['default']
export const LazyUiBreadcrumb: typeof import("../components/ui/breadcrumb")['default']
export const LazyUiButton: typeof import("../components/ui/button")['default']
export const LazyUiCalendar: typeof import("../components/ui/calendar")['default']
export const LazyUiCard: typeof import("../components/ui/card")['default']
export const LazyUiCarousel: typeof import("../components/ui/carousel")['default']
export const LazyUiChart: typeof import("../components/ui/chart")['default']
export const LazyUiCheckbox: typeof import("../components/ui/checkbox")['default']
export const LazyUiCollapsible: typeof import("../components/ui/collapsible")['default']
export const LazyUiCommand: typeof import("../components/ui/command")['default']
export const LazyUiContextMenu: typeof import("../components/ui/context-menu")['default']
export const LazyUiDialog: typeof import("../components/ui/dialog")['default']
export const LazyUiDrawer: typeof import("../components/ui/drawer")['default']
export const LazyUiDropdownMenu: typeof import("../components/ui/dropdown-menu")['default']
export const LazyUiForm: typeof import("../components/ui/form")['default']
export const LazyUiHoverCard: typeof import("../components/ui/hover-card")['default']
export const LazyUiInputOtp: typeof import("../components/ui/input-otp")['default']
export const LazyUiInput: typeof import("../components/ui/input")['default']
export const LazyUiLabel: typeof import("../components/ui/label")['default']
export const LazyUiMenubar: typeof import("../components/ui/menubar")['default']
export const LazyUiNavigationMenu: typeof import("../components/ui/navigation-menu")['default']
export const LazyUiPagination: typeof import("../components/ui/pagination")['default']
export const LazyUiPopover: typeof import("../components/ui/popover")['default']
export const LazyUiProgress: typeof import("../components/ui/progress")['default']
export const LazyUiRadioGroup: typeof import("../components/ui/radio-group")['default']
export const LazyUiResizable: typeof import("../components/ui/resizable")['default']
export const LazyUiScrollArea: typeof import("../components/ui/scroll-area")['default']
export const LazyUiSelect: typeof import("../components/ui/select")['default']
export const LazyUiSeparator: typeof import("../components/ui/separator")['default']
export const LazyUiSheet: typeof import("../components/ui/sheet")['default']
export const LazyUiSkeleton: typeof import("../components/ui/skeleton")['default']
export const LazyUiSlider: typeof import("../components/ui/slider")['default']
export const LazyUiSonner: typeof import("../components/ui/sonner")['default']
export const LazyUiSwitch: typeof import("../components/ui/switch")['default']
export const LazyUiTable: typeof import("../components/ui/table")['default']
export const LazyUiTabs: typeof import("../components/ui/tabs")['default']
export const LazyUiTextarea: typeof import("../components/ui/textarea")['default']
export const LazyUiToast: typeof import("../components/ui/toast")['default']
export const LazyUiToaster: typeof import("../components/ui/toaster")['default']
export const LazyUiToggleGroup: typeof import("../components/ui/toggle-group")['default']
export const LazyUiToggle: typeof import("../components/ui/toggle")['default']
export const LazyUiTooltip: typeof import("../components/ui/tooltip")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
