// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/6/2024, 8:10:28 AM
const configMerger = require("/home/projects/sb1-f8juha/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/projects/sb1-f8juha/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-f8juha/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-f8juha/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-f8juha/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-f8juha/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-f8juha/plugins/**/*.{js,ts,mjs}","/home/projects/sb1-f8juha/composables/**/*.{js,ts,mjs}","/home/projects/sb1-f8juha/utils/**/*.{js,ts,mjs}","/home/projects/sb1-f8juha/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-f8juha/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/projects/sb1-f8juha/app.config.{js,ts,mjs}"] } }));

module.exports = config
